<?php
$tmpName = $_FILES['upload_file']['tmp_name'];		//post from form
$mylista = file_get_contents($tmpName);			//load file into string
$mylistb = array_map('fgetcsv', file($tmpName));	//load file into array attempt 1
$mylistc = array_map('str_getcsv', file($tmpName));	//load file into array attempt 2


$ISA01 = "00";
$ISA02 = "          ";
$ISA03 ="00";
$ISA04 ="          ";
$ISA05 ="ZZ";
$ISA06 ="MERIA          ";
$ISA07 ="ZZ";
$ISA08 ="ROCKNEL        ";
$ISA09 = $CurrentTime1;
$ISA10 = $CurrentTime2;
$ISA11 = "U"
$ISA12 = "00401"
$ISA13 = $InterChangeControlNumberWithPadding;
$ISA14 = "0";
$ISA15 = "P";
$ISA16 = "<";
$GS01 = "SH";
$GS02 = "MEIRA";
$GS03 = "ROCKNEL";
$GS04 = $CurrentTime3;
$GS05 = $CurrentTime4;
$GS06 = $InterChangeControlNumberNoPadding;      
$GS07 = "X";
$GS08 = "004010";
$ST01 = "856";
$ST02 = "0001";
$BSN01 = "00";
$BSN02 = $ShipmentIdNo;
$BSN03 = $CurrentTime3;
$BSN04 = $CurrentTime2;
$DTM01 = $CurrentTime3;
$DTM02 = $CurrentTime2;		
$HL01 = "1";			//HL ID NUMBER
$HL02 = $HLSegments;		//Identifies the number of Hierachical Level segements Var no populated for Rocknel
$HL03 = "S";			//Identifies HL type as SHIPMENT
$MEA01 = "PD";			//Measurement Refrence ID code
$MEA02 = "G";			//Measurement Qualifer "G" is gross weight
$MEA03 = "55";			//Measurement Value "55" is a constant value chosen by rocknel this could change but does not.
$MEA04 = "LB";			//Used to Identify a composit unit of measure Rocknel uses LB for pounds but do not actually account for this value by weight
$TD101 = "CTN25";		//Identifies Packaging code as Carton
$TD102 = "9";			//Lading Quantity: should be number of cartons but plex does not require a count so this is fixed to an incorrect value of 9
$TD501 = "B";			//Routing sequence code. Per Plex Rocknel hardcodes this to "B" for Origin/Deliver Carrier 
$TD502 = "02";			// Identification Code qualifer is set to "02" as it is the standard Carrier Alpha Code
$TD503 = "LAWS";		//SCAC code of pickup carrier. Rocknel is set to a value of "LAWS" which is a fake carrier code created to fufill the requirement
$TD504 = "M";			//Transport method is set to a fixed value of "M" which standars for MOTOR(Common Carrier) *note: this isn't always true but fixed for Rocknel*
$TD301 = "TL";			//Equpment Discription code of "T" identifies Trailer as the equipment used for shipping. This is fixed for Rocknel even if another method is used. 
$TD302 = $SCACPICKUP;		//Value not used at rocknel. This would be A SCAC code for a pickup carrier. 
$TD303 = "654321";		//This is a fixed number not contained on the .CSV if it was used it would Identify the vessle used for shipment. Think license plate on a truck.
$REF101 = "BM";			//Refrence Number Qualifer is set to BM for Bill of Lading Number. Note: it could contain AW for Air Waybill number but rocknel fixes this to BM for all shipments. 
$REF102 = $ShipmentIdNo;	//This is the value of the BR or AR that is being shippped
$REF201 = "PK";			//This is supposed to be the Packing List Number but for Rocknel this is set to match the BR or AR. The value is fixed to PK.
$REF202 = $ShipmentIdNo;	//This is the value of the BR or AR that is being shippped
$N101 = "ST";			//Entity Identifer Code of "ST" means "ShipTo"
$N102 = $FreeFormNameST;	//A freeform name not used by Rocknel
$N103 = "92";			//Identification code qualifer of "92" for Assigned by Buyer or Buyer's Agent
$N104 = "ROCKNEL";		//Code Identifying Reciever
$N201 = "SF";			//Entity Identifer Code of "ST" means "ShipFrom"
$N202 = $FreeFormNameSF;	//A freeform name not used by Rocknel
$N203 = "01";			//Identification code qualifer of "01" for DUNS code... note this is a chosen value and not the actual Dun & Bradstreet Number
$N204 = "MEIRA"	;		//Code Identifing Sender

?>
